region                  = "us-west-2"
shared_credentials_file = "/Users/navaneethreddy/.aws/credentials"
profile                 = "default"
servicename             = "jenkins-worker-vpc"
cidr_block              = "192.168.0.0/16"