region                         = "us-east-1"
shared_credentials_file        = "/Users/navaneethreddy/.aws/credentials"
profile                        = "default"
servicename                    = "jenkins-vpc"
cidr_block                     = "10.0.0.0/16"